{% set name = "mermaid-py" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mermaid_py-{{ version }}.tar.gz
  sha256: 0cdff82752f927ddd8bb48ef1681ec46a38a78142a313eab31efb3e4753e955b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - requests >=2.31.0,<3.0.0

test:
  imports:
    - mermaid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://mermaidpy.vercel.app
  dev_url: https://github.com/ouhammmourachid/mermaid-py
  summary: A simple interface for the the famous lib mermaid-js to create diagrams.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
