{% set name = "mermaid-py" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mermaid_py-{{ version }}.tar.gz
  sha256: c4c23c4777a528f5e94d2788dfc7acccc94c9ff8bd86d6b7f44974ac4ce99821

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.31.0,<3.0.0

test:
  imports:
    - mermaid
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://mermaidpy.vercel.app
  dev_url: https://github.com/ouhammmourachid/mermaid-py
  summary: A simple interface for the the famous lib mermaid-js to create diagrams.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
